name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew bundleRelease
      
    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/bundle/release/app-release.aab
